BASE_YAML: "COCO-Detection/faster_rcnn_R_101_C4_3x.yaml"
DATASETS:
        TRAIN: ("daytime_clear_train",)
        TEST: ('daytime_clear_test','daytime_foggy_train',)
DATALOADER:
        NUM_WORKERS: 16
INPUT:
        MIN_SIZE_TRAIN: (600,)
        MIN_SIZE_TEST: 600
#        CLIP_RANDOM_CROPS: True
#        RANDOM_CROP_SIZE: 400

SOLVER:
        BASE_LR: 0.001
        MAX_ITER: 240000 #240000
        STEPS: [160000,] #[160000,]
        WARMUP_ITERS: 0
        IMS_PER_BATCH: 1
        CHECKPOINT_PERIOD: 20000  #权重保存间隔
MODEL:
#        BACKBONE:
#                NAME: ClipRN101
#        WEIGHTS: ""
#        CLIP_IMAGE_ENCODER_NAME: 'RN101'
#        META_ARCHITECTURE: 'ClipRCNNWithClipBackboneWithOffsetGenTrainable'

#        PROPOSAL_GENERATOR:
#                NAME: 'SBRPN'
        ROI_HEADS:
#                NAME: 'ClipRes5ROIHeadsAttn'
                # BATCH_SIZE_PER_IMAGE: 128   # faster, and good enough for this toy dataset (default: 512)
                NUM_CLASSES: 7
TEST:
        EVAL_SAVE_PERIOD: 20000
        EVAL_PERIOD: 20000 #测试间隔
OUTPUT_DIR: "all_outs/diverse_weather_fasterrcnn"
VIS_PERIOD: 20000
